<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fUvkX_R' shared service.

return $this->privates['.service_locator.fUvkX_R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminController::index' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\UserController::delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::edit' => ['privates', '.service_locator.5iM2kDV', 'get_ServiceLocator_5iM2kDVService.php', true],
    'App\\Controller\\UserController::index' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\UserController::new' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\UserController::show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\AdminController:index' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\UserController:delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:edit' => ['privates', '.service_locator.5iM2kDV', 'get_ServiceLocator_5iM2kDVService.php', true],
    'App\\Controller\\UserController:index' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\UserController:new' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\UserController:show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
], [
    'App\\Controller\\AdminController::index' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\UserController::delete' => '?',
    'App\\Controller\\UserController::edit' => '?',
    'App\\Controller\\UserController::index' => '?',
    'App\\Controller\\UserController::new' => '?',
    'App\\Controller\\UserController::show' => '?',
    'App\\Controller\\AdminController:index' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\SecurityController:register' => '?',
    'App\\Controller\\UserController:delete' => '?',
    'App\\Controller\\UserController:edit' => '?',
    'App\\Controller\\UserController:index' => '?',
    'App\\Controller\\UserController:new' => '?',
    'App\\Controller\\UserController:show' => '?',
]);
