<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQmK1hYn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQmK1hYn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQmK1hYn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQmK1hYn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQmK1hYn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QmK1hYn',
    'container.build_id' => '7e63a8bc',
    'container.build_time' => 1560352848,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQmK1hYn');
